project_id = "xlnzttdxmxuywxmwjmpd"

[functions.hotmart-webhook]
verify_jwt = false

[functions.hoopay-webhook]
verify_jwt = false

[functions.john-wick-chat]
verify_jwt = false

[functions.check-approved-email]
verify_jwt = false

[functions.graphql-proxy]
verify_jwt = false

[functions.roteirista-pro-chat]
verify_jwt = false
